name: Handle issues
on: issues
jobs:
    output-issue-info:
        runs-on: ubuntu-latest
        steps:
            - name: Output issue information
              run: |
                echo "Issue Title: ${{ github.event.issue.title }}"
                echo "Issue Body: ${{ github.event.issue.body }}"