name: deployment exercise
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        outputs:
            script-files: ${{ steps.upload-artifact.outputs.scriptfile }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name : cache node modules
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            - name: install dependencies
              run: npm ci
            - name: Linit code
              run: npm run lint
            - name: Run tests
              run: npm run test
            - name: Build application
              run: npm run build
            - name: Publish Js files
              id: publish-js
              run: find dist/assets/*.js -type f -execdir echo 'scriptfile={}'>> $GITHUB_OUTPUT ';'
            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: dist-files
                path: |
                    dist
    pre-stage:
        runs-on: ubuntu-latest
        needs: deploy
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: dist-files
            - name: check outputs
              run: ls
            - name: output filename
              run: echo ${{ needs.deploy.outputs.script-files }}